########################################
# script for running fastqc on raw data

import os
import logging
import subprocess

def run_post_merge_qc(Configuration):
    """
    Runs FastQC on symlinked FASTQ files in the processing directory.
    Output: HTML and zip files generated by FastQC in the QC directory.
    """

    # Define input directory for the processing data (symlinked files)
    processing_sample_dir = os.path.join(Configuration.Processing_dir, Configuration.file_to_process)
    
    # Check if processing directory exists, if not, log and exit
    if not os.path.exists(processing_sample_dir):
        logging.error(f"Processing directory {processing_sample_dir} not found. Please run the merging and linking process first.")
        raise Exception("Processing directory not found")

    # Get the symlinked files in the processing directory (R1 and R2)
    processing_RAW_files = os.listdir(processing_sample_dir)
    processing_RAW_files = [f for f in processing_RAW_files if f.endswith(".gz")]

    # Create QC output directory for this sample
    sample_qc_dir = os.path.join(Configuration.RAW_QC_dir, Configuration.file_to_process)
    os.makedirs(sample_qc_dir, exist_ok=True)

    # Log the start of FastQC
    logging.info(f"Running FastQC on symlinked data for {Configuration.file_to_process}")

    # Run FastQC on each symlinked file (R1 and R2)
    for file in processing_RAW_files:
        input_file = os.path.join(processing_sample_dir, file)
        output_prefix = os.path.join(sample_qc_dir, os.path.basename(file).replace(".gz", ""))  # remove .gz for output name

        # Run FastQC
        subprocess.run(["fastqc", "--outdir", sample_qc_dir, "-t", Configuration.num_cores, input_file])

        # Logging the result
        logging.info(f"FastQC completed for {file}. Output saved to {sample_qc_dir}")

    logging.info("Finished running FastQC on symlinked data.")
    
    
def run_post_trim_qc(Configuration):
    """
    Runs FastQC on the trimmed FASTQ files in the Trimmed directory.
    Output: HTML and zip files generated by FastQC in the QC directory.
    """

    # Define input directory for the trimmed data
    trimmed_sample_dir = os.path.join(Configuration.Trimmed_dir, Configuration.file_to_process)

    # Check if the trimmed directory exists, if not, log and exit
    if not os.path.exists(trimmed_sample_dir):
        logging.error(f"Trimmed directory {trimmed_sample_dir} not found. Please run the trimming process first.")
        raise Exception("Trimmed directory not found")

    # Get the trimmed files in the directory (R1 and R2)
    trimmed_RAW_files = os.listdir(trimmed_sample_dir)
    trimmed_RAW_files = [f for f in trimmed_RAW_files if f.endswith(".gz")]

    # Create QC output directory for this sample
    sample_qc_dir = os.path.join(Configuration.Trimmed_QC_dir, Configuration.file_to_process)
    os.makedirs(sample_qc_dir, exist_ok=True)

    # Log the start of FastQC
    logging.info(f"Running FastQC on trimmed data for {Configuration.file_to_process}")

    # Run FastQC on each trimmed file (R1 and R2)
    for file in trimmed_RAW_files:
        input_file = os.path.join(trimmed_sample_dir, file)
        output_prefix = os.path.join(sample_qc_dir, os.path.basename(file).replace(".gz", ""))  # remove .gz for output name

        # Run FastQC
        subprocess.run(["fastqc", "--outdir", sample_qc_dir, "-t", Configuration.num_cores, input_file])

        # Logging the result
        logging.info(f"FastQC completed for {file}. Output saved to {sample_qc_dir}")

    logging.info("Finished running FastQC on trimmed data.")